[tool.black]
line-length = 100
target-version = ["py39"]

[tool.ruff]
line-length = 100
target-version = "py39"
src = ["runs", "selector.py", "setup.py", "utils"]
exclude = ["old"]

[tool.ruff.lint]
extend-select = ["E", "F", "W", "I"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
